Updated for spacebrain requirements

diff --git a/streisand b/streisand
--- a/streisand
+++ b/streisand
@@ -90,7 +90,7 @@ function run_genesis() {
     GENESIS_INVENTORY=inventories/inventory
   fi
   # Customize the Streisand services that will be installed
-  customize
+  # customize
   # Ensure that the customization hasn't resulted in something inconsistent
   validate
   # Run the specified genesis playbook with the specified Ansible inventory
@@ -167,25 +167,27 @@ check_python
 check_ansible
 
 # Figure out which genesis role to invoke
-read -r -p "Which provider are you using?
-  1. Amazon
-  2. Azure
-  3. DigitalOcean
-  4. Google
-  5. Linode
-  6. Rackspace
-  7. Localhost (Advanced)
-  8. Existing Server (Advanced)
-: " reply
+# read -r -p "Which provider are you using?
+#   1. Amazon
+#   2. Azure
+#   3. DigitalOcean
+#   4. Google
+#   5. Linode
+#   6. Rackspace
+#   7. Localhost (Advanced)
+#   8. Existing Server (Advanced)
+# : " reply
+#
+# case "$reply" in
+#   1) run_genesis amazon.yml;;
+#   2) run_genesis azure.yml;;
+#   3) run_genesis digitalocean.yml;;
+#   4) run_genesis google.yml;;
+#   5) run_genesis linode.yml;;
+#   6) run_genesis rackspace.yml;;
+#   7) local_provision;;
+#   8) existing_server;;
+#   *) echo; echo "Invalid provider selected."; exit 1;;
+# esac
 
-case "$reply" in
-  1) run_genesis amazon.yml;;
-  2) run_genesis azure.yml;;
-  3) run_genesis digitalocean.yml;;
-  4) run_genesis google.yml;;
-  5) run_genesis linode.yml;;
-  6) run_genesis rackspace.yml;;
-  7) local_provision;;
-  8) existing_server;;
-  *) echo; echo "Invalid provider selected."; exit 1;;
-esac
+run_genesis amazon.yml
